language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath

install:
  - composer install -o
  - tests/travis/nginx/install-nginx.sh

script:
  - echo 'Hello world'